# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lie.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import linalg_pb2 as linalg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lie.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tlie.proto\x1a\x0clinalg.proto\"5\n\rQuaternionF64\x12\x16\n\x04imag\x18\x01 \x01(\x0b\x32\x08.Vec3F64\x12\x0c\n\x04real\x18\x02 \x01(\x01\"\x1d\n\x0cRotation2F64\x12\r\n\x05theta\x18\x01 \x01(\x01\"N\n\x0cIsometry2F64\x12\x1f\n\x08rotation\x18\x01 \x01(\x0b\x32\r.Rotation2F64\x12\x1d\n\x0btranslation\x18\x02 \x01(\x0b\x32\x08.Vec2F64\"7\n\x0cRotation3F64\x12\'\n\x0funit_quaternion\x18\x01 \x01(\x0b\x32\x0e.QuaternionF64\"N\n\x0cIsometry3F64\x12\x1f\n\x08rotation\x18\x01 \x01(\x0b\x32\r.Rotation3F64\x12\x1d\n\x0btranslation\x18\x02 \x01(\x0b\x32\x08.Vec3F64\"\\\n\x13Isometry3F64Tangent\x12!\n\x0flinear_velocity\x18\x01 \x01(\x0b\x32\x08.Vec3F64\x12\"\n\x10\x61ngular_velocity\x18\x02 \x01(\x0b\x32\x08.Vec3F64b\x06proto3')
  ,
  dependencies=[linalg__pb2.DESCRIPTOR,])




_QUATERNIONF64 = _descriptor.Descriptor(
  name='QuaternionF64',
  full_name='QuaternionF64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imag', full_name='QuaternionF64.imag', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='real', full_name='QuaternionF64.real', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=80,
)


_ROTATION2F64 = _descriptor.Descriptor(
  name='Rotation2F64',
  full_name='Rotation2F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta', full_name='Rotation2F64.theta', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=111,
)


_ISOMETRY2F64 = _descriptor.Descriptor(
  name='Isometry2F64',
  full_name='Isometry2F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rotation', full_name='Isometry2F64.rotation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translation', full_name='Isometry2F64.translation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=191,
)


_ROTATION3F64 = _descriptor.Descriptor(
  name='Rotation3F64',
  full_name='Rotation3F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unit_quaternion', full_name='Rotation3F64.unit_quaternion', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=248,
)


_ISOMETRY3F64 = _descriptor.Descriptor(
  name='Isometry3F64',
  full_name='Isometry3F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rotation', full_name='Isometry3F64.rotation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translation', full_name='Isometry3F64.translation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=328,
)


_ISOMETRY3F64TANGENT = _descriptor.Descriptor(
  name='Isometry3F64Tangent',
  full_name='Isometry3F64Tangent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear_velocity', full_name='Isometry3F64Tangent.linear_velocity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='Isometry3F64Tangent.angular_velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=422,
)

_QUATERNIONF64.fields_by_name['imag'].message_type = linalg__pb2._VEC3F64
_ISOMETRY2F64.fields_by_name['rotation'].message_type = _ROTATION2F64
_ISOMETRY2F64.fields_by_name['translation'].message_type = linalg__pb2._VEC2F64
_ROTATION3F64.fields_by_name['unit_quaternion'].message_type = _QUATERNIONF64
_ISOMETRY3F64.fields_by_name['rotation'].message_type = _ROTATION3F64
_ISOMETRY3F64.fields_by_name['translation'].message_type = linalg__pb2._VEC3F64
_ISOMETRY3F64TANGENT.fields_by_name['linear_velocity'].message_type = linalg__pb2._VEC3F64
_ISOMETRY3F64TANGENT.fields_by_name['angular_velocity'].message_type = linalg__pb2._VEC3F64
DESCRIPTOR.message_types_by_name['QuaternionF64'] = _QUATERNIONF64
DESCRIPTOR.message_types_by_name['Rotation2F64'] = _ROTATION2F64
DESCRIPTOR.message_types_by_name['Isometry2F64'] = _ISOMETRY2F64
DESCRIPTOR.message_types_by_name['Rotation3F64'] = _ROTATION3F64
DESCRIPTOR.message_types_by_name['Isometry3F64'] = _ISOMETRY3F64
DESCRIPTOR.message_types_by_name['Isometry3F64Tangent'] = _ISOMETRY3F64TANGENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuaternionF64 = _reflection.GeneratedProtocolMessageType('QuaternionF64', (_message.Message,), dict(
  DESCRIPTOR = _QUATERNIONF64,
  __module__ = 'lie_pb2'
  # @@protoc_insertion_point(class_scope:QuaternionF64)
  ))
_sym_db.RegisterMessage(QuaternionF64)

Rotation2F64 = _reflection.GeneratedProtocolMessageType('Rotation2F64', (_message.Message,), dict(
  DESCRIPTOR = _ROTATION2F64,
  __module__ = 'lie_pb2'
  # @@protoc_insertion_point(class_scope:Rotation2F64)
  ))
_sym_db.RegisterMessage(Rotation2F64)

Isometry2F64 = _reflection.GeneratedProtocolMessageType('Isometry2F64', (_message.Message,), dict(
  DESCRIPTOR = _ISOMETRY2F64,
  __module__ = 'lie_pb2'
  # @@protoc_insertion_point(class_scope:Isometry2F64)
  ))
_sym_db.RegisterMessage(Isometry2F64)

Rotation3F64 = _reflection.GeneratedProtocolMessageType('Rotation3F64', (_message.Message,), dict(
  DESCRIPTOR = _ROTATION3F64,
  __module__ = 'lie_pb2'
  # @@protoc_insertion_point(class_scope:Rotation3F64)
  ))
_sym_db.RegisterMessage(Rotation3F64)

Isometry3F64 = _reflection.GeneratedProtocolMessageType('Isometry3F64', (_message.Message,), dict(
  DESCRIPTOR = _ISOMETRY3F64,
  __module__ = 'lie_pb2'
  # @@protoc_insertion_point(class_scope:Isometry3F64)
  ))
_sym_db.RegisterMessage(Isometry3F64)

Isometry3F64Tangent = _reflection.GeneratedProtocolMessageType('Isometry3F64Tangent', (_message.Message,), dict(
  DESCRIPTOR = _ISOMETRY3F64TANGENT,
  __module__ = 'lie_pb2'
  # @@protoc_insertion_point(class_scope:Isometry3F64Tangent)
  ))
_sym_db.RegisterMessage(Isometry3F64Tangent)


# @@protoc_insertion_point(module_scope)
