# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import linalg_pb2 as linalg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculus.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63\x61lculus.proto\x1a\x0clinalg.proto\"7\n\tRegionI32\x12\x10\n\x08is_empty\x18\x01 \x01(\x08\x12\x0b\n\x03min\x18\x02 \x01(\x05\x12\x0b\n\x03max\x18\x03 \x01(\x05\"7\n\tRegionF32\x12\x10\n\x08is_empty\x18\x01 \x01(\x08\x12\x0b\n\x03min\x18\x02 \x01(\x02\x12\x0b\n\x03max\x18\x03 \x01(\x02\"7\n\tRegionF64\x12\x10\n\x08is_empty\x18\x01 \x01(\x08\x12\x0b\n\x03min\x18\x02 \x01(\x01\x12\x0b\n\x03max\x18\x03 \x01(\x01\"L\n\nRegion2F64\x12\x10\n\x08is_empty\x18\x01 \x01(\x08\x12\x15\n\x03min\x18\x02 \x01(\x0b\x32\x08.Vec2F64\x12\x15\n\x03max\x18\x03 \x01(\x0b\x32\x08.Vec2F64\"2\n\x14RepeatedG0Region2F64\x12\x1a\n\x05value\x18\x01 \x03(\x0b\x32\x0b.Region2F64b\x06proto3')
  ,
  dependencies=[linalg__pb2.DESCRIPTOR,])




_REGIONI32 = _descriptor.Descriptor(
  name='RegionI32',
  full_name='RegionI32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_empty', full_name='RegionI32.is_empty', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='RegionI32.min', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='RegionI32.max', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=87,
)


_REGIONF32 = _descriptor.Descriptor(
  name='RegionF32',
  full_name='RegionF32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_empty', full_name='RegionF32.is_empty', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='RegionF32.min', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='RegionF32.max', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=144,
)


_REGIONF64 = _descriptor.Descriptor(
  name='RegionF64',
  full_name='RegionF64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_empty', full_name='RegionF64.is_empty', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='RegionF64.min', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='RegionF64.max', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=201,
)


_REGION2F64 = _descriptor.Descriptor(
  name='Region2F64',
  full_name='Region2F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_empty', full_name='Region2F64.is_empty', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='Region2F64.min', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='Region2F64.max', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=279,
)


_REPEATEDG0REGION2F64 = _descriptor.Descriptor(
  name='RepeatedG0Region2F64',
  full_name='RepeatedG0Region2F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='RepeatedG0Region2F64.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=331,
)

_REGION2F64.fields_by_name['min'].message_type = linalg__pb2._VEC2F64
_REGION2F64.fields_by_name['max'].message_type = linalg__pb2._VEC2F64
_REPEATEDG0REGION2F64.fields_by_name['value'].message_type = _REGION2F64
DESCRIPTOR.message_types_by_name['RegionI32'] = _REGIONI32
DESCRIPTOR.message_types_by_name['RegionF32'] = _REGIONF32
DESCRIPTOR.message_types_by_name['RegionF64'] = _REGIONF64
DESCRIPTOR.message_types_by_name['Region2F64'] = _REGION2F64
DESCRIPTOR.message_types_by_name['RepeatedG0Region2F64'] = _REPEATEDG0REGION2F64
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegionI32 = _reflection.GeneratedProtocolMessageType('RegionI32', (_message.Message,), dict(
  DESCRIPTOR = _REGIONI32,
  __module__ = 'calculus_pb2'
  # @@protoc_insertion_point(class_scope:RegionI32)
  ))
_sym_db.RegisterMessage(RegionI32)

RegionF32 = _reflection.GeneratedProtocolMessageType('RegionF32', (_message.Message,), dict(
  DESCRIPTOR = _REGIONF32,
  __module__ = 'calculus_pb2'
  # @@protoc_insertion_point(class_scope:RegionF32)
  ))
_sym_db.RegisterMessage(RegionF32)

RegionF64 = _reflection.GeneratedProtocolMessageType('RegionF64', (_message.Message,), dict(
  DESCRIPTOR = _REGIONF64,
  __module__ = 'calculus_pb2'
  # @@protoc_insertion_point(class_scope:RegionF64)
  ))
_sym_db.RegisterMessage(RegionF64)

Region2F64 = _reflection.GeneratedProtocolMessageType('Region2F64', (_message.Message,), dict(
  DESCRIPTOR = _REGION2F64,
  __module__ = 'calculus_pb2'
  # @@protoc_insertion_point(class_scope:Region2F64)
  ))
_sym_db.RegisterMessage(Region2F64)

RepeatedG0Region2F64 = _reflection.GeneratedProtocolMessageType('RepeatedG0Region2F64', (_message.Message,), dict(
  DESCRIPTOR = _REPEATEDG0REGION2F64,
  __module__ = 'calculus_pb2'
  # @@protoc_insertion_point(class_scope:RepeatedG0Region2F64)
  ))
_sym_db.RegisterMessage(RepeatedG0Region2F64)


# @@protoc_insertion_point(module_scope)
