# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import uri_pb2 as uri__pb2
import event_pb2 as event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x65vent_service.proto\x1a\turi.proto\x1a\x0b\x65vent.proto\"6\n\x10SubscribeRequest\x12\x11\n\x03uri\x18\x01 \x01(\x0b\x32\x04.Uri\x12\x0f\n\x07\x65very_n\x18\x02 \x01(\r\"8\n\x0eSubscribeReply\x12\x15\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x06.Event\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"=\n\x13RequestReplyRequest\x12\x15\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x06.Event\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\";\n\x11RequestReplyReply\x12\x15\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x06.Event\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"X\n\x0cRequestReply\x12%\n\x07request\x18\x01 \x01(\x0b\x32\x14.RequestReplyRequest\x12!\n\x05reply\x18\x02 \x01(\x0b\x32\x12.RequestReplyReply\"\x11\n\x0fListUrisRequest\"#\n\rListUrisReply\x12\x12\n\x04uris\x18\x01 \x03(\x0b\x32\x04.Uri\"\xa7\x02\n\x12\x45ventServiceConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0c\n\x04host\x18\x03 \x01(\t\x12(\n\rsubscriptions\x18\x04 \x03(\x0b\x32\x11.SubscribeRequest\x12\x12\n\x04uris\x18\x05 \x03(\x0b\x32\x04.Uri\x12\x0c\n\x04\x61rgs\x18\x06 \x03(\t\x12/\n\tlog_level\x18\x07 \x01(\x0e\x32\x1c.EventServiceConfig.LogLevel\"j\n\x08LogLevel\x12\n\n\x06NOTSET\x10\x00\x12\x0c\n\x08\x43RITICAL\x10\x32\x12\t\n\x05\x46\x41TAL\x10\x32\x12\t\n\x05\x45RROR\x10(\x12\x0b\n\x07WARNING\x10\x1e\x12\x08\n\x04WARN\x10\x1e\x12\x08\n\x04INFO\x10\x14\x12\t\n\x05\x44\x45\x42UG\x10\n\x1a\x02\x10\x01\">\n\x16\x45ventServiceConfigList\x12$\n\x07\x63onfigs\x18\x01 \x03(\x0b\x32\x13.EventServiceConfig2\xaf\x01\n\x0c\x45ventService\x12.\n\x08listUris\x12\x10.ListUrisRequest\x1a\x0e.ListUrisReply\"\x00\x12\x33\n\tsubscribe\x12\x11.SubscribeRequest\x1a\x0f.SubscribeReply\"\x00\x30\x01\x12:\n\x0crequestReply\x12\x14.RequestReplyRequest\x1a\x12.RequestReplyReply\"\x00\x62\x06proto3')
  ,
  dependencies=[uri__pb2.DESCRIPTOR,event__pb2.DESCRIPTOR,])



_EVENTSERVICECONFIG_LOGLEVEL = _descriptor.EnumDescriptor(
  name='LogLevel',
  full_name='EventServiceConfig.LogLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL', index=1, number=50,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FATAL', index=2, number=50,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=3, number=40,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=4, number=30,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARN', index=5, number=30,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=6, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=7, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=_b('\020\001'),
  serialized_start=621,
  serialized_end=727,
)
_sym_db.RegisterEnumDescriptor(_EVENTSERVICECONFIG_LOGLEVEL)


_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='SubscribeRequest.uri', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='every_n', full_name='SubscribeRequest.every_n', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=101,
)


_SUBSCRIBEREPLY = _descriptor.Descriptor(
  name='SubscribeReply',
  full_name='SubscribeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='SubscribeReply.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='SubscribeReply.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=159,
)


_REQUESTREPLYREQUEST = _descriptor.Descriptor(
  name='RequestReplyRequest',
  full_name='RequestReplyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='RequestReplyRequest.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='RequestReplyRequest.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=222,
)


_REQUESTREPLYREPLY = _descriptor.Descriptor(
  name='RequestReplyReply',
  full_name='RequestReplyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='RequestReplyReply.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='RequestReplyReply.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=283,
)


_REQUESTREPLY = _descriptor.Descriptor(
  name='RequestReply',
  full_name='RequestReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='RequestReply.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reply', full_name='RequestReply.reply', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=373,
)


_LISTURISREQUEST = _descriptor.Descriptor(
  name='ListUrisRequest',
  full_name='ListUrisRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=392,
)


_LISTURISREPLY = _descriptor.Descriptor(
  name='ListUrisReply',
  full_name='ListUrisReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uris', full_name='ListUrisReply.uris', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=429,
)


_EVENTSERVICECONFIG = _descriptor.Descriptor(
  name='EventServiceConfig',
  full_name='EventServiceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='EventServiceConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='EventServiceConfig.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='EventServiceConfig.host', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subscriptions', full_name='EventServiceConfig.subscriptions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uris', full_name='EventServiceConfig.uris', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='EventServiceConfig.args', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_level', full_name='EventServiceConfig.log_level', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENTSERVICECONFIG_LOGLEVEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=727,
)


_EVENTSERVICECONFIGLIST = _descriptor.Descriptor(
  name='EventServiceConfigList',
  full_name='EventServiceConfigList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configs', full_name='EventServiceConfigList.configs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=729,
  serialized_end=791,
)

_SUBSCRIBEREQUEST.fields_by_name['uri'].message_type = uri__pb2._URI
_SUBSCRIBEREPLY.fields_by_name['event'].message_type = event__pb2._EVENT
_REQUESTREPLYREQUEST.fields_by_name['event'].message_type = event__pb2._EVENT
_REQUESTREPLYREPLY.fields_by_name['event'].message_type = event__pb2._EVENT
_REQUESTREPLY.fields_by_name['request'].message_type = _REQUESTREPLYREQUEST
_REQUESTREPLY.fields_by_name['reply'].message_type = _REQUESTREPLYREPLY
_LISTURISREPLY.fields_by_name['uris'].message_type = uri__pb2._URI
_EVENTSERVICECONFIG.fields_by_name['subscriptions'].message_type = _SUBSCRIBEREQUEST
_EVENTSERVICECONFIG.fields_by_name['uris'].message_type = uri__pb2._URI
_EVENTSERVICECONFIG.fields_by_name['log_level'].enum_type = _EVENTSERVICECONFIG_LOGLEVEL
_EVENTSERVICECONFIG_LOGLEVEL.containing_type = _EVENTSERVICECONFIG
_EVENTSERVICECONFIGLIST.fields_by_name['configs'].message_type = _EVENTSERVICECONFIG
DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['SubscribeReply'] = _SUBSCRIBEREPLY
DESCRIPTOR.message_types_by_name['RequestReplyRequest'] = _REQUESTREPLYREQUEST
DESCRIPTOR.message_types_by_name['RequestReplyReply'] = _REQUESTREPLYREPLY
DESCRIPTOR.message_types_by_name['RequestReply'] = _REQUESTREPLY
DESCRIPTOR.message_types_by_name['ListUrisRequest'] = _LISTURISREQUEST
DESCRIPTOR.message_types_by_name['ListUrisReply'] = _LISTURISREPLY
DESCRIPTOR.message_types_by_name['EventServiceConfig'] = _EVENTSERVICECONFIG
DESCRIPTOR.message_types_by_name['EventServiceConfigList'] = _EVENTSERVICECONFIGLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEREQUEST,
  __module__ = 'event_service_pb2'
  # @@protoc_insertion_point(class_scope:SubscribeRequest)
  ))
_sym_db.RegisterMessage(SubscribeRequest)

SubscribeReply = _reflection.GeneratedProtocolMessageType('SubscribeReply', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEREPLY,
  __module__ = 'event_service_pb2'
  # @@protoc_insertion_point(class_scope:SubscribeReply)
  ))
_sym_db.RegisterMessage(SubscribeReply)

RequestReplyRequest = _reflection.GeneratedProtocolMessageType('RequestReplyRequest', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTREPLYREQUEST,
  __module__ = 'event_service_pb2'
  # @@protoc_insertion_point(class_scope:RequestReplyRequest)
  ))
_sym_db.RegisterMessage(RequestReplyRequest)

RequestReplyReply = _reflection.GeneratedProtocolMessageType('RequestReplyReply', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTREPLYREPLY,
  __module__ = 'event_service_pb2'
  # @@protoc_insertion_point(class_scope:RequestReplyReply)
  ))
_sym_db.RegisterMessage(RequestReplyReply)

RequestReply = _reflection.GeneratedProtocolMessageType('RequestReply', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTREPLY,
  __module__ = 'event_service_pb2'
  # @@protoc_insertion_point(class_scope:RequestReply)
  ))
_sym_db.RegisterMessage(RequestReply)

ListUrisRequest = _reflection.GeneratedProtocolMessageType('ListUrisRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTURISREQUEST,
  __module__ = 'event_service_pb2'
  # @@protoc_insertion_point(class_scope:ListUrisRequest)
  ))
_sym_db.RegisterMessage(ListUrisRequest)

ListUrisReply = _reflection.GeneratedProtocolMessageType('ListUrisReply', (_message.Message,), dict(
  DESCRIPTOR = _LISTURISREPLY,
  __module__ = 'event_service_pb2'
  # @@protoc_insertion_point(class_scope:ListUrisReply)
  ))
_sym_db.RegisterMessage(ListUrisReply)

EventServiceConfig = _reflection.GeneratedProtocolMessageType('EventServiceConfig', (_message.Message,), dict(
  DESCRIPTOR = _EVENTSERVICECONFIG,
  __module__ = 'event_service_pb2'
  # @@protoc_insertion_point(class_scope:EventServiceConfig)
  ))
_sym_db.RegisterMessage(EventServiceConfig)

EventServiceConfigList = _reflection.GeneratedProtocolMessageType('EventServiceConfigList', (_message.Message,), dict(
  DESCRIPTOR = _EVENTSERVICECONFIGLIST,
  __module__ = 'event_service_pb2'
  # @@protoc_insertion_point(class_scope:EventServiceConfigList)
  ))
_sym_db.RegisterMessage(EventServiceConfigList)


_EVENTSERVICECONFIG_LOGLEVEL._options = None

_EVENTSERVICE = _descriptor.ServiceDescriptor(
  name='EventService',
  full_name='EventService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=794,
  serialized_end=969,
  methods=[
  _descriptor.MethodDescriptor(
    name='listUris',
    full_name='EventService.listUris',
    index=0,
    containing_service=None,
    input_type=_LISTURISREQUEST,
    output_type=_LISTURISREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='subscribe',
    full_name='EventService.subscribe',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_SUBSCRIBEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='requestReply',
    full_name='EventService.requestReply',
    index=2,
    containing_service=None,
    input_type=_REQUESTREPLYREQUEST,
    output_type=_REQUESTREPLYREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTSERVICE)

DESCRIPTOR.services_by_name['EventService'] = _EVENTSERVICE

# @@protoc_insertion_point(module_scope)
