# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='examples.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x65xamples.proto\",\n\x0eStructExample1\x12\x0f\n\x07integer\x18\x01 \x01(\x01\x12\t\n\x01\x66\x18\x02 \x01(\x02\"<\n\x0eStructExample2\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x03\x65x1\x18\x02 \x01(\x0b\x32\x0f.StructExample1b\x06proto3')
)




_STRUCTEXAMPLE1 = _descriptor.Descriptor(
  name='StructExample1',
  full_name='StructExample1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='integer', full_name='StructExample1.integer', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f', full_name='StructExample1.f', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=62,
)


_STRUCTEXAMPLE2 = _descriptor.Descriptor(
  name='StructExample2',
  full_name='StructExample2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='StructExample2.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ex1', full_name='StructExample2.ex1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=124,
)

_STRUCTEXAMPLE2.fields_by_name['ex1'].message_type = _STRUCTEXAMPLE1
DESCRIPTOR.message_types_by_name['StructExample1'] = _STRUCTEXAMPLE1
DESCRIPTOR.message_types_by_name['StructExample2'] = _STRUCTEXAMPLE2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StructExample1 = _reflection.GeneratedProtocolMessageType('StructExample1', (_message.Message,), dict(
  DESCRIPTOR = _STRUCTEXAMPLE1,
  __module__ = 'examples_pb2'
  # @@protoc_insertion_point(class_scope:StructExample1)
  ))
_sym_db.RegisterMessage(StructExample1)

StructExample2 = _reflection.GeneratedProtocolMessageType('StructExample2', (_message.Message,), dict(
  DESCRIPTOR = _STRUCTEXAMPLE2,
  __module__ = 'examples_pb2'
  # @@protoc_insertion_point(class_scope:StructExample2)
  ))
_sym_db.RegisterMessage(StructExample2)


# @@protoc_insertion_point(module_scope)
