# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import linalg_pb2 as linalg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geometry.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0egeometry.proto\x1a\x0clinalg.proto\"%\n\x0bUnitVec3F64\x12\x16\n\x04vec3\x18\x01 \x01(\x0b\x32\x08.Vec3F64\">\n\x0eHyperplane3F64\x12\x1c\n\x06normal\x18\x01 \x01(\x0b\x32\x0c.UnitVec3F64\x12\x0e\n\x06offset\x18\x02 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[linalg__pb2.DESCRIPTOR,])




_UNITVEC3F64 = _descriptor.Descriptor(
  name='UnitVec3F64',
  full_name='UnitVec3F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vec3', full_name='UnitVec3F64.vec3', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=69,
)


_HYPERPLANE3F64 = _descriptor.Descriptor(
  name='Hyperplane3F64',
  full_name='Hyperplane3F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='normal', full_name='Hyperplane3F64.normal', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='Hyperplane3F64.offset', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=133,
)

_UNITVEC3F64.fields_by_name['vec3'].message_type = linalg__pb2._VEC3F64
_HYPERPLANE3F64.fields_by_name['normal'].message_type = _UNITVEC3F64
DESCRIPTOR.message_types_by_name['UnitVec3F64'] = _UNITVEC3F64
DESCRIPTOR.message_types_by_name['Hyperplane3F64'] = _HYPERPLANE3F64
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnitVec3F64 = _reflection.GeneratedProtocolMessageType('UnitVec3F64', (_message.Message,), dict(
  DESCRIPTOR = _UNITVEC3F64,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:UnitVec3F64)
  ))
_sym_db.RegisterMessage(UnitVec3F64)

Hyperplane3F64 = _reflection.GeneratedProtocolMessageType('Hyperplane3F64', (_message.Message,), dict(
  DESCRIPTOR = _HYPERPLANE3F64,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:Hyperplane3F64)
  ))
_sym_db.RegisterMessage(Hyperplane3F64)


# @@protoc_insertion_point(module_scope)
