# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bimage.proto\"*\n\tImageSize\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"<\n\x0bImageLayout\x12\x18\n\x04size\x18\x01 \x01(\x0b\x32\n.ImageSize\x12\x13\n\x0bpitch_bytes\x18\x02 \x01(\r\"[\n\x0bPixelFormat\x12\x13\n\x0bnumber_type\x18\x01 \x01(\t\x12\x16\n\x0enum_components\x18\x02 \x01(\x05\x12\x1f\n\x17num_bytes_per_component\x18\x03 \x01(\x05\"Z\n\x08\x44ynImage\x12\x1c\n\x06layout\x18\x01 \x01(\x0b\x32\x0c.ImageLayout\x12\"\n\x0cpixel_format\x18\x02 \x01(\x0b\x32\x0c.PixelFormat\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x62\x06proto3')
)




_IMAGESIZE = _descriptor.Descriptor(
  name='ImageSize',
  full_name='ImageSize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ImageSize.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ImageSize.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=57,
)


_IMAGELAYOUT = _descriptor.Descriptor(
  name='ImageLayout',
  full_name='ImageLayout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='ImageLayout.size', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch_bytes', full_name='ImageLayout.pitch_bytes', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=119,
)


_PIXELFORMAT = _descriptor.Descriptor(
  name='PixelFormat',
  full_name='PixelFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_type', full_name='PixelFormat.number_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_components', full_name='PixelFormat.num_components', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_bytes_per_component', full_name='PixelFormat.num_bytes_per_component', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=212,
)


_DYNIMAGE = _descriptor.Descriptor(
  name='DynImage',
  full_name='DynImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layout', full_name='DynImage.layout', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_format', full_name='DynImage.pixel_format', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='DynImage.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=304,
)

_IMAGELAYOUT.fields_by_name['size'].message_type = _IMAGESIZE
_DYNIMAGE.fields_by_name['layout'].message_type = _IMAGELAYOUT
_DYNIMAGE.fields_by_name['pixel_format'].message_type = _PIXELFORMAT
DESCRIPTOR.message_types_by_name['ImageSize'] = _IMAGESIZE
DESCRIPTOR.message_types_by_name['ImageLayout'] = _IMAGELAYOUT
DESCRIPTOR.message_types_by_name['PixelFormat'] = _PIXELFORMAT
DESCRIPTOR.message_types_by_name['DynImage'] = _DYNIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageSize = _reflection.GeneratedProtocolMessageType('ImageSize', (_message.Message,), dict(
  DESCRIPTOR = _IMAGESIZE,
  __module__ = 'image_pb2'
  # @@protoc_insertion_point(class_scope:ImageSize)
  ))
_sym_db.RegisterMessage(ImageSize)

ImageLayout = _reflection.GeneratedProtocolMessageType('ImageLayout', (_message.Message,), dict(
  DESCRIPTOR = _IMAGELAYOUT,
  __module__ = 'image_pb2'
  # @@protoc_insertion_point(class_scope:ImageLayout)
  ))
_sym_db.RegisterMessage(ImageLayout)

PixelFormat = _reflection.GeneratedProtocolMessageType('PixelFormat', (_message.Message,), dict(
  DESCRIPTOR = _PIXELFORMAT,
  __module__ = 'image_pb2'
  # @@protoc_insertion_point(class_scope:PixelFormat)
  ))
_sym_db.RegisterMessage(PixelFormat)

DynImage = _reflection.GeneratedProtocolMessageType('DynImage', (_message.Message,), dict(
  DESCRIPTOR = _DYNIMAGE,
  __module__ = 'image_pb2'
  # @@protoc_insertion_point(class_scope:DynImage)
  ))
_sym_db.RegisterMessage(DynImage)


# @@protoc_insertion_point(module_scope)
