# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: linalg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='linalg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0clinalg.proto\"\x1f\n\x07Vec2I64\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\"\x1f\n\x07Vec2F32\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x1f\n\x07Vec2F64\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"*\n\x07Vec3I64\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\x12\t\n\x01z\x18\x03 \x01(\x03\"*\n\x07Vec3F32\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"*\n\x07Vec3F64\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\";\n\x07Mat2F32\x12\x17\n\x05\x63ol_0\x18\x01 \x01(\x0b\x32\x08.Vec2F32\x12\x17\n\x05\x63ol_1\x18\x02 \x01(\x0b\x32\x08.Vec2F32\";\n\x07Mat2F64\x12\x17\n\x05\x63ol_0\x18\x01 \x01(\x0b\x32\x08.Vec2F64\x12\x17\n\x05\x63ol_1\x18\x02 \x01(\x0b\x32\x08.Vec2F64\"T\n\x07Mat3F32\x12\x17\n\x05\x63ol_0\x18\x01 \x01(\x0b\x32\x08.Vec3F32\x12\x17\n\x05\x63ol_1\x18\x02 \x01(\x0b\x32\x08.Vec3F32\x12\x17\n\x05\x63ol_2\x18\x03 \x01(\x0b\x32\x08.Vec3F32\"T\n\x07Mat3F64\x12\x17\n\x05\x63ol_0\x18\x01 \x01(\x0b\x32\x08.Vec3F64\x12\x17\n\x05\x63ol_1\x18\x02 \x01(\x0b\x32\x08.Vec3F64\x12\x17\n\x05\x63ol_2\x18\x03 \x01(\x0b\x32\x08.Vec3F64\"\x17\n\x07VecXF32\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\"\x17\n\x07VecXF64\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"3\n\x07MatXF32\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02\"3\n\x07MatXF64\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02\x62\x06proto3')
)




_VEC2I64 = _descriptor.Descriptor(
  name='Vec2I64',
  full_name='Vec2I64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vec2I64.x', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vec2I64.y', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=47,
)


_VEC2F32 = _descriptor.Descriptor(
  name='Vec2F32',
  full_name='Vec2F32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vec2F32.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vec2F32.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=80,
)


_VEC2F64 = _descriptor.Descriptor(
  name='Vec2F64',
  full_name='Vec2F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vec2F64.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vec2F64.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=113,
)


_VEC3I64 = _descriptor.Descriptor(
  name='Vec3I64',
  full_name='Vec3I64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vec3I64.x', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vec3I64.y', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Vec3I64.z', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=157,
)


_VEC3F32 = _descriptor.Descriptor(
  name='Vec3F32',
  full_name='Vec3F32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vec3F32.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vec3F32.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Vec3F32.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=201,
)


_VEC3F64 = _descriptor.Descriptor(
  name='Vec3F64',
  full_name='Vec3F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vec3F64.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vec3F64.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Vec3F64.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=245,
)


_MAT2F32 = _descriptor.Descriptor(
  name='Mat2F32',
  full_name='Mat2F32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col_0', full_name='Mat2F32.col_0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='col_1', full_name='Mat2F32.col_1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=306,
)


_MAT2F64 = _descriptor.Descriptor(
  name='Mat2F64',
  full_name='Mat2F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col_0', full_name='Mat2F64.col_0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='col_1', full_name='Mat2F64.col_1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=367,
)


_MAT3F32 = _descriptor.Descriptor(
  name='Mat3F32',
  full_name='Mat3F32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col_0', full_name='Mat3F32.col_0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='col_1', full_name='Mat3F32.col_1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='col_2', full_name='Mat3F32.col_2', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=453,
)


_MAT3F64 = _descriptor.Descriptor(
  name='Mat3F64',
  full_name='Mat3F64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col_0', full_name='Mat3F64.col_0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='col_1', full_name='Mat3F64.col_1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='col_2', full_name='Mat3F64.col_2', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=539,
)


_VECXF32 = _descriptor.Descriptor(
  name='VecXF32',
  full_name='VecXF32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='VecXF32.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=564,
)


_VECXF64 = _descriptor.Descriptor(
  name='VecXF64',
  full_name='VecXF64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='VecXF64.data', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=589,
)


_MATXF32 = _descriptor.Descriptor(
  name='MatXF32',
  full_name='MatXF32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='MatXF32.rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cols', full_name='MatXF32.cols', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='MatXF32.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=642,
)


_MATXF64 = _descriptor.Descriptor(
  name='MatXF64',
  full_name='MatXF64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='MatXF64.rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cols', full_name='MatXF64.cols', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='MatXF64.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=644,
  serialized_end=695,
)

_MAT2F32.fields_by_name['col_0'].message_type = _VEC2F32
_MAT2F32.fields_by_name['col_1'].message_type = _VEC2F32
_MAT2F64.fields_by_name['col_0'].message_type = _VEC2F64
_MAT2F64.fields_by_name['col_1'].message_type = _VEC2F64
_MAT3F32.fields_by_name['col_0'].message_type = _VEC3F32
_MAT3F32.fields_by_name['col_1'].message_type = _VEC3F32
_MAT3F32.fields_by_name['col_2'].message_type = _VEC3F32
_MAT3F64.fields_by_name['col_0'].message_type = _VEC3F64
_MAT3F64.fields_by_name['col_1'].message_type = _VEC3F64
_MAT3F64.fields_by_name['col_2'].message_type = _VEC3F64
DESCRIPTOR.message_types_by_name['Vec2I64'] = _VEC2I64
DESCRIPTOR.message_types_by_name['Vec2F32'] = _VEC2F32
DESCRIPTOR.message_types_by_name['Vec2F64'] = _VEC2F64
DESCRIPTOR.message_types_by_name['Vec3I64'] = _VEC3I64
DESCRIPTOR.message_types_by_name['Vec3F32'] = _VEC3F32
DESCRIPTOR.message_types_by_name['Vec3F64'] = _VEC3F64
DESCRIPTOR.message_types_by_name['Mat2F32'] = _MAT2F32
DESCRIPTOR.message_types_by_name['Mat2F64'] = _MAT2F64
DESCRIPTOR.message_types_by_name['Mat3F32'] = _MAT3F32
DESCRIPTOR.message_types_by_name['Mat3F64'] = _MAT3F64
DESCRIPTOR.message_types_by_name['VecXF32'] = _VECXF32
DESCRIPTOR.message_types_by_name['VecXF64'] = _VECXF64
DESCRIPTOR.message_types_by_name['MatXF32'] = _MATXF32
DESCRIPTOR.message_types_by_name['MatXF64'] = _MATXF64
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vec2I64 = _reflection.GeneratedProtocolMessageType('Vec2I64', (_message.Message,), dict(
  DESCRIPTOR = _VEC2I64,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:Vec2I64)
  ))
_sym_db.RegisterMessage(Vec2I64)

Vec2F32 = _reflection.GeneratedProtocolMessageType('Vec2F32', (_message.Message,), dict(
  DESCRIPTOR = _VEC2F32,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:Vec2F32)
  ))
_sym_db.RegisterMessage(Vec2F32)

Vec2F64 = _reflection.GeneratedProtocolMessageType('Vec2F64', (_message.Message,), dict(
  DESCRIPTOR = _VEC2F64,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:Vec2F64)
  ))
_sym_db.RegisterMessage(Vec2F64)

Vec3I64 = _reflection.GeneratedProtocolMessageType('Vec3I64', (_message.Message,), dict(
  DESCRIPTOR = _VEC3I64,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:Vec3I64)
  ))
_sym_db.RegisterMessage(Vec3I64)

Vec3F32 = _reflection.GeneratedProtocolMessageType('Vec3F32', (_message.Message,), dict(
  DESCRIPTOR = _VEC3F32,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:Vec3F32)
  ))
_sym_db.RegisterMessage(Vec3F32)

Vec3F64 = _reflection.GeneratedProtocolMessageType('Vec3F64', (_message.Message,), dict(
  DESCRIPTOR = _VEC3F64,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:Vec3F64)
  ))
_sym_db.RegisterMessage(Vec3F64)

Mat2F32 = _reflection.GeneratedProtocolMessageType('Mat2F32', (_message.Message,), dict(
  DESCRIPTOR = _MAT2F32,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:Mat2F32)
  ))
_sym_db.RegisterMessage(Mat2F32)

Mat2F64 = _reflection.GeneratedProtocolMessageType('Mat2F64', (_message.Message,), dict(
  DESCRIPTOR = _MAT2F64,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:Mat2F64)
  ))
_sym_db.RegisterMessage(Mat2F64)

Mat3F32 = _reflection.GeneratedProtocolMessageType('Mat3F32', (_message.Message,), dict(
  DESCRIPTOR = _MAT3F32,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:Mat3F32)
  ))
_sym_db.RegisterMessage(Mat3F32)

Mat3F64 = _reflection.GeneratedProtocolMessageType('Mat3F64', (_message.Message,), dict(
  DESCRIPTOR = _MAT3F64,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:Mat3F64)
  ))
_sym_db.RegisterMessage(Mat3F64)

VecXF32 = _reflection.GeneratedProtocolMessageType('VecXF32', (_message.Message,), dict(
  DESCRIPTOR = _VECXF32,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:VecXF32)
  ))
_sym_db.RegisterMessage(VecXF32)

VecXF64 = _reflection.GeneratedProtocolMessageType('VecXF64', (_message.Message,), dict(
  DESCRIPTOR = _VECXF64,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:VecXF64)
  ))
_sym_db.RegisterMessage(VecXF64)

MatXF32 = _reflection.GeneratedProtocolMessageType('MatXF32', (_message.Message,), dict(
  DESCRIPTOR = _MATXF32,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:MatXF32)
  ))
_sym_db.RegisterMessage(MatXF32)

MatXF64 = _reflection.GeneratedProtocolMessageType('MatXF64', (_message.Message,), dict(
  DESCRIPTOR = _MATXF64,
  __module__ = 'linalg_pb2'
  # @@protoc_insertion_point(class_scope:MatXF64)
  ))
_sym_db.RegisterMessage(MatXF64)


# @@protoc_insertion_point(module_scope)
