# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recorder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import event_service_pb2 as event__service__pb2
import timestamp_pb2 as timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='recorder.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0erecorder.proto\x1a\x13\x65vent_service.proto\x1a\x0ftimestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"t\n\x0fRecorderProfile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\rsubscriptions\x18\x02 \x03(\x0b\x32\x11.SubscribeRequest\x12)\n\x08metadata\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"`\n\x12RecorderAnnotation\x12\x1a\n\x06stamps\x18\x01 \x03(\x0b\x32\n.Timestamp\x12\x1d\n\x04kind\x18\x02 \x01(\x0e\x32\x0f.AnnotationKind\x12\x0f\n\x07message\x18\x03 \x01(\t*\xbc\x01\n\x0e\x41nnotationKind\x12\x16\n\x12\x41NNOTATION_UNKNOWN\x10\x00\x12\x18\n\x14\x41NNOTATION_ROW_START\x10\x01\x12\x16\n\x12\x41NNOTATION_ROW_END\x10\x02\x12\x19\n\x15\x41NNOTATION_PATH_START\x10\x03\x12\x17\n\x13\x41NNOTATION_PATH_END\x10\x04\x12\x17\n\x13\x41NNOTATION_WAYPOINT\x10\x05\x12\x13\n\x0f\x41NNOTATION_NOTE\x10\x06\x62\x06proto3')
  ,
  dependencies=[event__service__pb2.DESCRIPTOR,timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])

_ANNOTATIONKIND = _descriptor.EnumDescriptor(
  name='AnnotationKind',
  full_name='AnnotationKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ANNOTATION_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANNOTATION_ROW_START', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANNOTATION_ROW_END', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANNOTATION_PATH_START', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANNOTATION_PATH_END', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANNOTATION_WAYPOINT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANNOTATION_NOTE', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=303,
  serialized_end=491,
)
_sym_db.RegisterEnumDescriptor(_ANNOTATIONKIND)

AnnotationKind = enum_type_wrapper.EnumTypeWrapper(_ANNOTATIONKIND)
ANNOTATION_UNKNOWN = 0
ANNOTATION_ROW_START = 1
ANNOTATION_ROW_END = 2
ANNOTATION_PATH_START = 3
ANNOTATION_PATH_END = 4
ANNOTATION_WAYPOINT = 5
ANNOTATION_NOTE = 6



_RECORDERPROFILE = _descriptor.Descriptor(
  name='RecorderProfile',
  full_name='RecorderProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RecorderProfile.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subscriptions', full_name='RecorderProfile.subscriptions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='RecorderProfile.metadata', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=202,
)


_RECORDERANNOTATION = _descriptor.Descriptor(
  name='RecorderAnnotation',
  full_name='RecorderAnnotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamps', full_name='RecorderAnnotation.stamps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='RecorderAnnotation.kind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='RecorderAnnotation.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=300,
)

_RECORDERPROFILE.fields_by_name['subscriptions'].message_type = event__service__pb2._SUBSCRIBEREQUEST
_RECORDERPROFILE.fields_by_name['metadata'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_RECORDERANNOTATION.fields_by_name['stamps'].message_type = timestamp__pb2._TIMESTAMP
_RECORDERANNOTATION.fields_by_name['kind'].enum_type = _ANNOTATIONKIND
DESCRIPTOR.message_types_by_name['RecorderProfile'] = _RECORDERPROFILE
DESCRIPTOR.message_types_by_name['RecorderAnnotation'] = _RECORDERANNOTATION
DESCRIPTOR.enum_types_by_name['AnnotationKind'] = _ANNOTATIONKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecorderProfile = _reflection.GeneratedProtocolMessageType('RecorderProfile', (_message.Message,), dict(
  DESCRIPTOR = _RECORDERPROFILE,
  __module__ = 'recorder_pb2'
  # @@protoc_insertion_point(class_scope:RecorderProfile)
  ))
_sym_db.RegisterMessage(RecorderProfile)

RecorderAnnotation = _reflection.GeneratedProtocolMessageType('RecorderAnnotation', (_message.Message,), dict(
  DESCRIPTOR = _RECORDERANNOTATION,
  __module__ = 'recorder_pb2'
  # @@protoc_insertion_point(class_scope:RecorderAnnotation)
  ))
_sym_db.RegisterMessage(RecorderAnnotation)


# @@protoc_insertion_point(module_scope)
