# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import image_pb2 as image__pb2
import lie_pb2 as lie__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0csensor.proto\x1a\x0bimage.proto\x1a\tlie.proto\"V\n\x0b\x43\x61meraModel\x12\x1e\n\nimage_size\x18\x01 \x01(\x0b\x32\n.ImageSize\x12\x17\n\x0f\x64istortion_type\x18\x02 \x01(\t\x12\x0e\n\x06params\x18\x03 \x03(\x01\"3\n\x0c\x43\x61meraModels\x12#\n\rcamera_models\x18\x01 \x03(\x0b\x32\x0c.CameraModel\"+\n\x0e\x43lippingPlanes\x12\x0c\n\x04near\x18\x01 \x01(\x02\x12\x0b\n\x03\x66\x61r\x18\x02 \x01(\x02\"W\n\x0bRigidCamera\x12 \n\nintrinsics\x18\x01 \x01(\x0b\x32\x0c.CameraModel\x12&\n\x0frig_from_camera\x18\x02 \x01(\x0b\x32\r.Isometry3F64\"/\n\tGyroModel\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x03(\x01\"3\n\rAcceleroModel\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x03(\x01\"R\n\x08ImuModel\x12\x1e\n\ngyro_model\x18\x01 \x01(\x0b\x32\n.GyroModel\x12&\n\x0e\x61\x63\x63\x65lero_model\x18\x02 \x01(\x0b\x32\x0e.AcceleroModelb\x06proto3')
  ,
  dependencies=[image__pb2.DESCRIPTOR,lie__pb2.DESCRIPTOR,])




_CAMERAMODEL = _descriptor.Descriptor(
  name='CameraModel',
  full_name='CameraModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_size', full_name='CameraModel.image_size', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distortion_type', full_name='CameraModel.distortion_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='CameraModel.params', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=126,
)


_CAMERAMODELS = _descriptor.Descriptor(
  name='CameraModels',
  full_name='CameraModels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_models', full_name='CameraModels.camera_models', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=179,
)


_CLIPPINGPLANES = _descriptor.Descriptor(
  name='ClippingPlanes',
  full_name='ClippingPlanes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='near', full_name='ClippingPlanes.near', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='far', full_name='ClippingPlanes.far', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=224,
)


_RIGIDCAMERA = _descriptor.Descriptor(
  name='RigidCamera',
  full_name='RigidCamera',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='intrinsics', full_name='RigidCamera.intrinsics', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rig_from_camera', full_name='RigidCamera.rig_from_camera', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=313,
)


_GYROMODEL = _descriptor.Descriptor(
  name='GyroModel',
  full_name='GyroModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_type', full_name='GyroModel.model_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='GyroModel.params', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=362,
)


_ACCELEROMODEL = _descriptor.Descriptor(
  name='AcceleroModel',
  full_name='AcceleroModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_type', full_name='AcceleroModel.model_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='AcceleroModel.params', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=415,
)


_IMUMODEL = _descriptor.Descriptor(
  name='ImuModel',
  full_name='ImuModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gyro_model', full_name='ImuModel.gyro_model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accelero_model', full_name='ImuModel.accelero_model', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=499,
)

_CAMERAMODEL.fields_by_name['image_size'].message_type = image__pb2._IMAGESIZE
_CAMERAMODELS.fields_by_name['camera_models'].message_type = _CAMERAMODEL
_RIGIDCAMERA.fields_by_name['intrinsics'].message_type = _CAMERAMODEL
_RIGIDCAMERA.fields_by_name['rig_from_camera'].message_type = lie__pb2._ISOMETRY3F64
_IMUMODEL.fields_by_name['gyro_model'].message_type = _GYROMODEL
_IMUMODEL.fields_by_name['accelero_model'].message_type = _ACCELEROMODEL
DESCRIPTOR.message_types_by_name['CameraModel'] = _CAMERAMODEL
DESCRIPTOR.message_types_by_name['CameraModels'] = _CAMERAMODELS
DESCRIPTOR.message_types_by_name['ClippingPlanes'] = _CLIPPINGPLANES
DESCRIPTOR.message_types_by_name['RigidCamera'] = _RIGIDCAMERA
DESCRIPTOR.message_types_by_name['GyroModel'] = _GYROMODEL
DESCRIPTOR.message_types_by_name['AcceleroModel'] = _ACCELEROMODEL
DESCRIPTOR.message_types_by_name['ImuModel'] = _IMUMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraModel = _reflection.GeneratedProtocolMessageType('CameraModel', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAMODEL,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:CameraModel)
  ))
_sym_db.RegisterMessage(CameraModel)

CameraModels = _reflection.GeneratedProtocolMessageType('CameraModels', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAMODELS,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:CameraModels)
  ))
_sym_db.RegisterMessage(CameraModels)

ClippingPlanes = _reflection.GeneratedProtocolMessageType('ClippingPlanes', (_message.Message,), dict(
  DESCRIPTOR = _CLIPPINGPLANES,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:ClippingPlanes)
  ))
_sym_db.RegisterMessage(ClippingPlanes)

RigidCamera = _reflection.GeneratedProtocolMessageType('RigidCamera', (_message.Message,), dict(
  DESCRIPTOR = _RIGIDCAMERA,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:RigidCamera)
  ))
_sym_db.RegisterMessage(RigidCamera)

GyroModel = _reflection.GeneratedProtocolMessageType('GyroModel', (_message.Message,), dict(
  DESCRIPTOR = _GYROMODEL,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:GyroModel)
  ))
_sym_db.RegisterMessage(GyroModel)

AcceleroModel = _reflection.GeneratedProtocolMessageType('AcceleroModel', (_message.Message,), dict(
  DESCRIPTOR = _ACCELEROMODEL,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:AcceleroModel)
  ))
_sym_db.RegisterMessage(AcceleroModel)

ImuModel = _reflection.GeneratedProtocolMessageType('ImuModel', (_message.Message,), dict(
  DESCRIPTOR = _IMUMODEL,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:ImuModel)
  ))
_sym_db.RegisterMessage(ImuModel)


# @@protoc_insertion_point(module_scope)
