name: Lint black

on:
  push:
    paths:
      - '*.py'
  pull_request:
    paths:
      - '*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable